// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package cn.lmh.examples.grpc.proto;

public final class Greeting {
  private Greeting() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Point_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Point_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Rectangle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Rectangle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocationNote_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LocationNote_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RouteSummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RouteSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Greeting.proto\",\n\005Point\022\020\n\010latitude\030\001 " +
      "\001(\005\022\021\n\tlongitude\030\002 \001(\005\"3\n\tRectangle\022\022\n\002l" +
      "o\030\001 \001(\0132\006.Point\022\022\n\002hi\030\002 \001(\0132\006.Point\";\n\014L" +
      "ocationNote\022\030\n\010location\030\001 \001(\0132\006.Point\022\021\n" +
      "\ttimestamp\030\002 \001(\003\"9\n\014RouteSummary\022\023\n\013poin" +
      "t_count\030\001 \001(\005\022\024\n\014elapsed_time\030\002 \001(\0032\260\001\n\n" +
      "RouteGuide\022#\n\010getPoint\022\006.Point\032\r.Locatio" +
      "nNote\"\000\022$\n\nlistPoints\022\n.Rectangle\032\006.Poin" +
      "t\"\0000\001\022(\n\013recordRoute\022\006.Point\032\r.RouteSumm" +
      "ary\"\000(\001\022-\n\016getPointStream\022\006.Point\032\r.Rout" +
      "eSummary\"\000(\0010\001B\036\n\032cn.lmh.examples.grpc.p" +
      "rotoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Point_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
    internal_static_Rectangle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Rectangle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Rectangle_descriptor,
        new java.lang.String[] { "Lo", "Hi", });
    internal_static_LocationNote_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LocationNote_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LocationNote_descriptor,
        new java.lang.String[] { "Location", "Timestamp", });
    internal_static_RouteSummary_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RouteSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RouteSummary_descriptor,
        new java.lang.String[] { "PointCount", "ElapsedTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
