// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package cn.lmh.examples.grpc.proto;

public interface LocationNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LocationNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  boolean hasLocation();
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  cn.lmh.examples.grpc.proto.Point getLocation();
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  cn.lmh.examples.grpc.proto.PointOrBuilder getLocationOrBuilder();

  /**
   * <pre>
   * The message to be sent.
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
