// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package cn.lmh.examples.grpc.proto;

/**
 * <pre>
 * A LocationNote is a message sent while at a given point.
 * </pre>
 *
 * Protobuf type {@code LocationNote}
 */
public  final class LocationNote extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LocationNote)
    LocationNoteOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationNote.newBuilder() to construct.
  private LocationNote(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationNote() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LocationNote();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationNote(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            cn.lmh.examples.grpc.proto.Point.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(cn.lmh.examples.grpc.proto.Point.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.lmh.examples.grpc.proto.Greeting.internal_static_LocationNote_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.lmh.examples.grpc.proto.Greeting.internal_static_LocationNote_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.lmh.examples.grpc.proto.LocationNote.class, cn.lmh.examples.grpc.proto.LocationNote.Builder.class);
  }

  public static final int LOCATION_FIELD_NUMBER = 1;
  private cn.lmh.examples.grpc.proto.Point location_;
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  public cn.lmh.examples.grpc.proto.Point getLocation() {
    return location_ == null ? cn.lmh.examples.grpc.proto.Point.getDefaultInstance() : location_;
  }
  /**
   * <pre>
   * The location from which the message is sent.
   * </pre>
   *
   * <code>.Point location = 1;</code>
   */
  public cn.lmh.examples.grpc.proto.PointOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private long timestamp_;
  /**
   * <pre>
   * The message to be sent.
   * </pre>
   *
   * <code>int64 timestamp = 2;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (location_ != null) {
      output.writeMessage(1, getLocation());
    }
    if (timestamp_ != 0L) {
      output.writeInt64(2, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLocation());
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.lmh.examples.grpc.proto.LocationNote)) {
      return super.equals(obj);
    }
    cn.lmh.examples.grpc.proto.LocationNote other = (cn.lmh.examples.grpc.proto.LocationNote) obj;

    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.lmh.examples.grpc.proto.LocationNote parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.lmh.examples.grpc.proto.LocationNote prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A LocationNote is a message sent while at a given point.
   * </pre>
   *
   * Protobuf type {@code LocationNote}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LocationNote)
      cn.lmh.examples.grpc.proto.LocationNoteOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.lmh.examples.grpc.proto.Greeting.internal_static_LocationNote_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.lmh.examples.grpc.proto.Greeting.internal_static_LocationNote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.lmh.examples.grpc.proto.LocationNote.class, cn.lmh.examples.grpc.proto.LocationNote.Builder.class);
    }

    // Construct using cn.lmh.examples.grpc.proto.LocationNote.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      timestamp_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.lmh.examples.grpc.proto.Greeting.internal_static_LocationNote_descriptor;
    }

    @java.lang.Override
    public cn.lmh.examples.grpc.proto.LocationNote getDefaultInstanceForType() {
      return cn.lmh.examples.grpc.proto.LocationNote.getDefaultInstance();
    }

    @java.lang.Override
    public cn.lmh.examples.grpc.proto.LocationNote build() {
      cn.lmh.examples.grpc.proto.LocationNote result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.lmh.examples.grpc.proto.LocationNote buildPartial() {
      cn.lmh.examples.grpc.proto.LocationNote result = new cn.lmh.examples.grpc.proto.LocationNote(this);
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.lmh.examples.grpc.proto.LocationNote) {
        return mergeFrom((cn.lmh.examples.grpc.proto.LocationNote)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.lmh.examples.grpc.proto.LocationNote other) {
      if (other == cn.lmh.examples.grpc.proto.LocationNote.getDefaultInstance()) return this;
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.lmh.examples.grpc.proto.LocationNote parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.lmh.examples.grpc.proto.LocationNote) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private cn.lmh.examples.grpc.proto.Point location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.lmh.examples.grpc.proto.Point, cn.lmh.examples.grpc.proto.Point.Builder, cn.lmh.examples.grpc.proto.PointOrBuilder> locationBuilder_;
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public cn.lmh.examples.grpc.proto.Point getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? cn.lmh.examples.grpc.proto.Point.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public Builder setLocation(cn.lmh.examples.grpc.proto.Point value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public Builder setLocation(
        cn.lmh.examples.grpc.proto.Point.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public Builder mergeLocation(cn.lmh.examples.grpc.proto.Point value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            cn.lmh.examples.grpc.proto.Point.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public cn.lmh.examples.grpc.proto.Point.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    public cn.lmh.examples.grpc.proto.PointOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            cn.lmh.examples.grpc.proto.Point.getDefaultInstance() : location_;
      }
    }
    /**
     * <pre>
     * The location from which the message is sent.
     * </pre>
     *
     * <code>.Point location = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        cn.lmh.examples.grpc.proto.Point, cn.lmh.examples.grpc.proto.Point.Builder, cn.lmh.examples.grpc.proto.PointOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            cn.lmh.examples.grpc.proto.Point, cn.lmh.examples.grpc.proto.Point.Builder, cn.lmh.examples.grpc.proto.PointOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The message to be sent.
     * </pre>
     *
     * <code>int64 timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LocationNote)
  }

  // @@protoc_insertion_point(class_scope:LocationNote)
  private static final cn.lmh.examples.grpc.proto.LocationNote DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.lmh.examples.grpc.proto.LocationNote();
  }

  public static cn.lmh.examples.grpc.proto.LocationNote getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationNote>
      PARSER = new com.google.protobuf.AbstractParser<LocationNote>() {
    @java.lang.Override
    public LocationNote parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationNote(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationNote> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationNote> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.lmh.examples.grpc.proto.LocationNote getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

