// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package cn.lmh.examples.grpc.proto;

public interface RectangleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Rectangle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   */
  boolean hasLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   */
  cn.lmh.examples.grpc.proto.Point getLo();
  /**
   * <pre>
   * One corner of the rectangle.
   * </pre>
   *
   * <code>.Point lo = 1;</code>
   */
  cn.lmh.examples.grpc.proto.PointOrBuilder getLoOrBuilder();

  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   */
  boolean hasHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   */
  cn.lmh.examples.grpc.proto.Point getHi();
  /**
   * <pre>
   * The other corner of the rectangle.
   * </pre>
   *
   * <code>.Point hi = 2;</code>
   */
  cn.lmh.examples.grpc.proto.PointOrBuilder getHiOrBuilder();
}
