// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeting.proto

package cn.lmh.examples.grpc.proto;

public interface RouteSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RouteSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The number of points received.
   * </pre>
   *
   * <code>int32 point_count = 1;</code>
   */
  int getPointCount();

  /**
   * <pre>
   * The duration of the traversal in seconds.
   * </pre>
   *
   * <code>int64 elapsed_time = 2;</code>
   */
  long getElapsedTime();
}
